# Lists

In [4]:
list1 = [1,2]
list2 = [4,5]
list3 = list1 + list2 #concatenation

print(list3)

[1, 2, 4, 5]


In [5]:
print(list1*3) #repetition

[1, 2, 1, 2, 1, 2]


In [6]:
8 in list1  #test membership

False

In [8]:
mylist = [1,2,'Hello',True, 5.98, 16]

print(mylist[2:5]) #slicing

['Hello', True, 5.98]


In [9]:
print(mylist[1:6:2]) #extended slicing, 3rd parameter is for step value

[2, True, 16]


In [12]:
mylist[2:5] = [] #deletion
print(mylist)

del mylist[0]
print(mylist)

[1, 2]
[2]


In [21]:
#methods to grow list
mylist = [1,2]

mylist.append(6)
print(mylist)

mylist.extend(range(3))
print(mylist)

mylist.insert(3, 'hi')
print(mylist)

[1, 2, 6]
[1, 2, 6, 0, 1, 2]
[1, 2, 6, 'hi', 0, 1, 2]


In [23]:
#methods to shrink list

mylist.pop(4)
print(mylist)

mylist.remove('hi')
print(mylist)

#mylist.clear()
#print(mylist)

[1, 2, 6, 'hi', 1, 2]
[1, 2, 6, 1, 2]


In [36]:
#searching and sorting

print(mylist.index(6))

print(mylist.count(2))

mylist2 = mylist.copy()
print(mylist2)

mylist2.reverse()
print(mylist2)

mylist2.sort()
print(mylist2)

mylist2.sort(reverse = True)
print(mylist2)

2
2
[2, 1, 6, 2, 1]
[1, 2, 6, 1, 2]
[1, 1, 2, 2, 6]
[6, 2, 2, 1, 1]


In [54]:
#Vectors and matrices
import numpy as np

myArr = np.array([1,2,3,4])
print(myArr)

myArr = np.arange(3,8)
print(myArr)

myArr = np.linspace(3,15,5) #creates a linearly spaced vector with 5 values in the inclusive range of 3 and 15
print(myArr)

myArr = np.tile(myArr, 3)
print(myArr)

myArr.shape

#special arrays

arr = np.zeros([2,3])
print(arr)

arr2 = np.ones([3,2])
print(arr2)

[1 2 3 4]
[3 4 5 6 7]
[ 3.  6.  9. 12. 15.]
[ 3.  6.  9. 12. 15.  3.  6.  9. 12. 15.  3.  6.  9. 12. 15.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [55]:
print(arr@arr2) #matrix multiplication

[[0. 0.]
 [0. 0.]]


In [67]:
class myList:
    def __init__(self, mylist):
        self.list = mylist
        self.r = len(mylist)
    
    def get(self,r):
        if r < 0 or r > self.r - 1:
            return('Index Error')
        else:
            return self.list[r]
        
    def setTo(self, r ,e):
        if r < 0 or r> self.r - 1:
            return('Index Error')
        else:
            x = self.list[r]
            self.list[r] = e
            return self.list


In [68]:
l = myList([1,2,3,4,5])

l.setTo(4,4)

[1, 2, 3, 4, 4]

# Linked Lists

storing an element is relative to other elements in the list

In [34]:
class Node:
    def __init__(self, data = None, next = None, prev = None):
        self.data = data
        self.next = next
        self.prev = prev

class LinkedList:
    def __init__(self):
        self.head = None

    #add  node at the front

    def push(self, newData):
        newNode = Node(data = newData)

        newNode.next = self.head
        newNode.prev = None

        if self.head is not None:
            self.head.prev = newNode

        self.head = newNode

    #add a node after a given node

    def insertAfter(self, prevNode, newData):
        if prevNode is None:
            print('This node doesnt exist')
            return
        
        newNode = Node(data = newData, prev = prevNode)

        newNode.next = prevNode.next

        if prevNode.next is not None:
            prevNode.next.prev = newNode

        newNode.prev = prevNode
        prevNode.next = newNode

    #add node at the end

    def append(self, newData):

        newNode = Node(data = newData)

        last = self.head #assign last to the first node in the list

        if self.head is None: #if the list is empty
            newNode.prev = None
            self.head = newNode
            return
        
        while (last.next is not None):
            last = last.next #assign the last node of the list to last

        last.next = newNode #let the next node of the last node be new node
        newNode.prev = last #link the previous node of the new node as last node


    #add a node before a given node

    def insertBefore(self, nextNode, newData):
        if nextNode == None:
            print('the given next node cannot be NULL')
            return
        
        newNode = Node(data = newData)

        newNode.prev = nextNode.prev
        nextNode.prev = newNode

        newNode.next = nextNode

        if newNode.prev != None:
            newNode.prev.next = newNode

        else:
            self.head = newNode

    def remove(self, node):
        t = node.data

        if node == self.head:
            self.head = self.head.next
            return
        (node.prev).next = node.next
        (node.next).prev = node.prev
        node.prev = None
        node.next = None

        return t
        

    def printList(self, node):
        last = None
        print('forward traversal: ')

        while (node != None):
            print(node.data, end = " ")
            last = node
            node = node.next

        print('\nreverse traversal: ')

        while (last != None):
            print(last.data, end = " ")
            last = last.prev




In [36]:
llist = LinkedList()

#1
llist.push(1)

# 4-1
llist.push(4)

#4-1-6
llist.append(6)

#4-2-1-6
llist.insertBefore(llist.head.next,2)

#4-1-6
llist.remove(llist.head.next)

llist.printList(llist.head)


forward traversal: 
4 1 6 
reverse traversal: 
6 1 4 

# Stacks 

LIFO: objects may be inserted into a stack at any time, but only the most recently inserted (the last onject) can be removed at any time

## Array based implementation

Must specify some maximum size $N$ for stack $S$

if stack is empty, $t = -1$

number of elements in stack $= t+1$

In [54]:
class Stack:
    def __init__(self):
        self.N = 50
        self.t = -1
        self.S = [None]*(self.N)

    def push(self, x):
        if (self.t)+1 == self.N:
            return ('Error: Stack Full')
        
        else:
            self.t += 1
            self.S[self.t] = x

    def pop(self):

        if self.t < 0:
            return ('Error: Stack empty')
        else:
            e = self.S[self.t]
            self.S[self.t] = None
            self.t -=1
            return e

    def printStack(self):
        print(self.S)
    

In [55]:
elements = Stack()

elements.push(1)
elements.push(3)
elements.push(5)

elements.pop()

elements.printStack()

[1, 3, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]


## computing spans

Given an array $X$, span $S[i]$ of $X[i]$ is the maximum number of consecutive elements $X[j]$ immediately preceding $X[i]$ such that $X[j] \leq X[i]$ with $j \leq i$